name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_HOME: empty
      ANDROID_NDK: empty
      ANDROID_SDK_HOME: empty
      KRITA_ROOT: empty
      KRITA_BUILD: empty
    

    steps:

         
     - name: check update ubuntu and install other deps
       run: |
             sudo apt-get update ;
             sudo apt-get install meson ninja-build ; 
             
             
             
     - name: Create Folders
       run : |
             mkdir build install android-ndk android-sdk;
             ls
             cd build;
             echo "KRITA_BUILD=$(pwd)" >> $GITHUB_ENV ;
             
     - name: Download NDK file
       
       run : |
            
             cd android-ndk;
             curl https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip -o ndk.zip ;
             ls ;
             unzip ndk.zip ;
     - name : Check Ndk file
       run: |
            cd android-ndk/android-ndk-r22b;
            ls;
            pwd;
            echo "ANDROID_NDK_HOME=$(pwd)" >> $GITHUB_ENV ;
            echo "ANDROID_NDK=$(pwd)" >> $GITHUB_ENV ;
            echo $ANDROID_NDK_HOME  ;
            echo $ANDROID_NDK  ;
            
     - name : Download SDK file
       run: |
              cd android-sdk ;
              curl https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip --output sdk.zip
              ls;
              unzip sdk.zip;
              cd cmdline-tools;
              ls ;
              pwd;
              cd bin;
              pwd;
              ls ;
              echo "ANDROID_SDK_HOME=$(pwd)" >> $GITHUB_ENV ;
              echo $ANDROID_SDK_HOME  ;
     - name : Installing SDK 
       run: |
             mkdir sdk;
             cd $ANDROID_SDK_HOME ;
             ls ;
             yes | ./sdkmanager --licenses --sdk_root=$ANDROID_SDK_HOME ;
             yes | ./sdkmanager platform-tools --sdk_root=$ANDROID_SDK_HOME ;
             yes | ./sdkmanager "platforms;android-21" --sdk_root=$ANDROID_SDK_HOME ;
             yes | ./sdkmanager "platforms;android-28" --sdk_root=$ANDROID_SDK_HOME ;
             yes | ./sdkmanager "build-tools;28.0.2" --sdk_root=$ANDROID_SDK_HOME ;
             ./sdkmanager --licenses --sdk_root=$ANDROID_SDK_HOME ;
            
     - name : check sdk
       run: | 
             cd $ANDROID_SDK_HOME;
             ls ;
     - name : Download krita
       run: |
             curl https://invent.kde.org/graphics/krita/-/archive/krita/5.1/krita-krita-5.1.zip -o krita.zip ;
             unzip krita.zip ;
             mv krita-krita-5.1 krita
             cd krita ;
             pwd ;
             echo "KRITA_ROOT=$(pwd)" >> $GITHUB_ENV ;
             ls ;
     - name : Android Build
       run: |
            cd krita/packaging/android ;
            export CC=/usr/bin/clang \
            export CXX=/usr/bin/clang++ \
            ./androidbuild.sh -p=all --src=$KRITA_ROOT --build-type=Debug --build-root=$KRITA_BUILD --ndk-path=$ANDROID_NDK_HOME --sdk-path=$ANDROID_SDK_HOME --api-level=21 --android-abi=armeabi-v7a
        
